### ISSUE TITLE
item.contextItems.push is not a function.

### ISSUE THREAD

**Issue by viktorbarati** [Snarling/bitburner-scripts#2]
https://github.com/Snarling/bitburner-scripts/blob/c7b8d11d7f2b85cb8cbf6c8f7f2216239e871fcf/box/examples/timekeeper.js#L16

Here item.contextItems.push is not a function. If you use your own push function it works, like:
item.addContextItem("Toogle Numbers", () => ...etc...);

**Comment by Snarling** [comment]
The old reference to push has been fixed in timekeeper.js. Sorry, hadn't been keeping all the examples up to date.
